---
abstract: 'Higher-level UA features for HTTP::Tiny'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  IO::Dir: '0'
  IO::File: '0'
  IO::Socket::INET: '0'
  List::Util: '0'
  Test::More: '0.88'
  lib: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Tiny-UA
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  HTTP::Tiny::UA:
    file: lib/HTTP/Tiny/UA.pm
    version: '0.002'
  HTTP::Tiny::UA::Response:
    file: lib/HTTP/Tiny/UA/Response.pm
    version: '0.002'
requires:
  Class::Tiny: '0'
  HTTP::Tiny: '0.036'
  perl: v5.10.0
  strict: '0'
  superclass: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/HTTP-Tiny-UA/issues
  homepage: https://github.com/dagolden/HTTP-Tiny-UA
  repository: https://github.com/dagolden/HTTP-Tiny-UA.git
version: '0.002'
x_authority: cpan:DAGOLDEN
